In [1]:
import numpy as np

In [2]:
#Numpy Array from a list

In [3]:
list1=[2,3,5,7,8,10,23]

In [4]:
array1=np.array(list1)

In [5]:
array1

array([ 2,  3,  5,  7,  8, 10, 23])

In [6]:
array1.shape

(7,)

In [7]:
list2=[[1,4,5,73,23],[13,5,23,23,1]]

In [8]:
array2=np.array(list2)

In [9]:
array2

array([[ 1,  4,  5, 73, 23],
       [13,  5, 23, 23,  1]])

In [11]:
array2.shape

(2, 5)

In [12]:
array2.reshape((1,10))

array([[ 1,  4,  5, 73, 23, 13,  5, 23, 23,  1]])

In [10]:
#Defining a Range

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(0.11,3)

array([0.11, 1.11, 2.11])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(1,2,9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [2]:
array3=np.random.randint(20,50,10)

In [20]:
array3.min()

20

In [21]:
array2.min()

1

In [22]:
array2.max()

73

In [23]:
array2.argmin()

0

In [24]:
array2.argmax()

3

In [6]:
arr1=np.array([1,2,3,4,5])

In [5]:
arr2=np.array([9,8,10,11,12])

In [7]:
arr1*arr2

array([ 9, 16, 30, 44, 60])

In [8]:
arr1/arr2

array([0.11111111, 0.25      , 0.3       , 0.36363636, 0.41666667])

In [9]:
arr1+arr2

array([10, 10, 13, 15, 17])

In [10]:
arr1-arr2

array([-8, -6, -7, -7, -7])

In [11]:
arr1-4

array([-3, -2, -1,  0,  1])

In [12]:
arr1+4

array([5, 6, 7, 8, 9])

In [13]:
arr1*4

array([ 4,  8, 12, 16, 20])

In [14]:
arr1/4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [15]:
np.median(arr1)

3.0

In [16]:
np.mean(arr1)

3.0